### ISSUE TITLE
Support custom S3 object storage

### ISSUE THREAD

**Issue by hanygirgis** [chainloop-dev/chainloop#1053]
Chainloop currently supports AWS S3 storage as a CAS backend :
https://docs.chainloop.dev/reference/operator/cas-backend/

It would be very useful if it can also support alternative S3-compliant storage systems, like MinIO.

Thanks!

**Comment by migmartri** [comment]
This makes all sense @hanygirgis! We'll give it a crack and hopefully land it in our release early next week :)

**Comment by migmartri** [comment]
Something that we should probably do is to move our S3 uploader module to golang v2 https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
