### ISSUE TITLE
CAS: Add support for GCP Secret Manager

### ISSUE THREAD

**Issue by gr0** [chainloop-dev/chainloop#108]
Right now CAS provides support for AWS secret manager and Hashicorp Vault. It would be awesome to have support for GCP Secret Manager.

**Comment by migmartri** [comment]
hi @gr0 thanks for filling the issue.

I agree, this could be a great addition specially for those running Chainloop in GKE. 

In case it helps. There is some sort of encapsulation already defined to achieve the addition of alternative backends, which long story short should be implementing this interface 
https://github.com/chainloop-dev/chainloop/blob/90c67652f78b231f0f472c01df1626cdb783a27b/internal/credentials/credentials.go#L32-L44

In addition to adding the backend to the `credentials` package, you'll need to a) add support to configuring (providing GCP auth) both at the ControlPlane and CAS i.e https://github.com/chainloop-dev/chainloop/blob/90c67652f78b231f0f472c01df1626cdb783a27b/app/controlplane/internal/conf/conf.proto#L94-L98

and b) bootstrap the new backend if needed as seen here https://github.com/chainloop-dev/chainloop/blob/90c67652f78b231f0f472c01df1626cdb783a27b/app/controlplane/cmd/main.go#L160 

Let me know if this is smth you'd like to work on and I'll be happy to assign the issue to you :)

Thank you!

**Comment by migmartri** [comment]
I am reopening this issue to tackle the deployment part, that way the feature can be used end to end.

https://github.com/chainloop-dev/chainloop/issues/134
