### ISSUE TITLE
Prometheus collector

### ISSUE THREAD

**Issue by javirln** [chainloop-dev/chainloop#1098]
The idea of the issue is for Chainloop to have an authenticated endpoint where users can retrieve Prometheus metrics about their organizations.

One base collector with a defined set of metrics that, for the first version, runs every time there is a request to the endpoint and gather the metrics. It needs to be authenticated with a valid Chainloop API Token.

Endpoint: `/prom/{org_name}/metrics`.

This collector will potentially be the default collector for all Prometheus registries defined by the Chainloop's business logic to expose metrics to customers, that is something like the following:
```golang
func (rm *ChainloopRegistryManager) AddRegistry(reg *ChainloopPrometheusRegistry) {
	collector := metrics.NewBaseChainloopCollector(reg.ID, rm.orgmetrics)

	reg.MustRegister(collector)
	rm.Registries = append(rm.Registries, reg)
}
```
In the above example there is the concept of RegistryManager which is in charged of:

- Keep track of all Prometheus registries being created for users within the lifecycle of the control plane.
- Register new Prometheus integrations by periodically checking the Integrations table assigning them the custom Chainloop collector.

**Comment by migmartri** [comment]
@javirln could you please create a subtask about making sure permissions for pulling data from prometheus is mapped in casbin and checked in the endpoint?

Thanks!
