### ISSUE TITLE
Improve policy results format

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1321]
Currently, policy evaluations are reported as a single `violations` rule result, that will contain elements in the case of non compliance. 
However, if the policy couldn't be evaluated (because of invalid input or some conditions were not met) it would still report an empty `violations` set, which is wrong, since it couldn't be evaluated.
There are three variables in policy evaluations:
* does it need to be evaluated? : we know this because of the policy selection logic (by kind and/or material name)
* was it evaluated?: this would come from the Rego itself
* violations

The proposal is to add a structured output to policies, leaving room for future improvements:
```
{
    "result": {
        "evaluated": true,
        "violations": []
    },
    "violations": [] // <-- current policy output
  }
```
How `evaluated` is generated, it's up to each policy implementation. For example, a CycloneDX policy would set it if there are `components` in the report, or a SARIF policy for trivy would set it if `runs[].tool.driver.name == "Trivy"`.

**Comment by jiparis** [comment]
Policy template with an example of the `result` rule:
``# DO NOT TOUCH THIS SECTION

default message := ""

message = m if {
    not valid_input
    m := "invalid input"
}

message = m if {
    valid_input
    count(violations) > 0
    m := "there were violations"
}

result = r if {
	r := {
	    "passed": passed,
	    "violations": violations,
          "message": message,
	}
}

default passed := false

passed if {
	valid_input
	count(violations) == 0
}

#############
# FILL BELOW
#############

# current chainloop policy main rule
violations contains msg if {
  ...
}

valid_input if {
  ...
}
```

**Comment by javirln** [comment]
Just a thought. Instead of hardcoding the values on the template that, can be potentially modified. We could create an internal package with just that information that the engine can load along with the main rego script so it will be like:
- Auxiliary internal package with the initializing content.
- Expose user written rego script that must import the initialization package.

**Comment by jiparis** [comment]
Thanks @javirln , unfortunately rules must be placed in the main script. We could externalize some logic, however, our engine only supports external packages when those are local and referenced with `file://` (not tested).
