### ISSUE TITLE
Document how-to write custom policies

### ISSUE THREAD

**Issue by jiparis** [chainloop-dev/chainloop#1391]
Improve https://docs.chainloop.dev/reference/policies with a How-to write custom policies, including:
* Policy template
* Rule expectations
* Rego tips
* Some examples and links to Rego playground.

**Comment by migmartri** [comment]
we have a how-to-guides section in the docs that we could leverage, i.e [https://docs.chainloop.dev/guides/sbom-management/](https://docs.chainloop.dev/guides/sbom-management/)
