### ISSUE TITLE
Store attestations in CAS

### ISSUE THREAD

**Issue by danlishka** [chainloop-dev/chainloop#262]
I would like to have the option to download attestations in the same way we currently can get materials.

```
chainloop artifact download --digest sha256:9be6e32ee1715a759...
```

With just one sha256, this will allow me to share easily:
- attestations,
- all referenced materials and artifacts.

We will need to start storing attestations in CAS as we do in case of integrations (please check the attached screenshot).
<img width="301" alt="Screenshot 2023-07-20 at 22 42 50" src="https://github.com/chainloop-dev/chainloop/assets/4465/396fd875-6349-430a-acda-82ee02f6fe91">

**Comment by migmartri** [comment]
Makes sense. Note that we used to store attestations in the CAS backend before https://github.com/chainloop-dev/chainloop/pull/180 but moved to DB.

The main difference between before and now, is that we want to add the attestation just for `download` purposes and in addition to DB, which will not make it a requirement per-se I think.
