### ISSUE TITLE
AWS S3 in CAS proxy

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#269]
The CAS proxy is a layer in front of different CAS backends. At the moment of this writing only OCI repositories are supported.

![image](https://github.com/chainloop-dev/chainloop/assets/24523/1da999ab-12b9-4f00-b160-9b48dd3d8312)

THe goal of this task is to

- [ ] Allow the artifact CAS proxy to be able to support more than 1 provider (OCI, S3) at the same time
- [ ] The specific provider (OCI, S3) could be selected on the fly in each request, so in addition to receiving the `credentials reference` now it will also receive the backend type.
- [ ] Implement AWS s3 blob storage CAS backend

![image](https://github.com/chainloop-dev/chainloop/assets/24523/5a3d7ecd-5c76-4555-adc0-88998b938619)

**Comment by danlishka** [comment]
What if we first add support for AWS S3 and then we will tackle a way to have a CAS proxy? Or we need to do both at the same time?

**Comment by migmartri** [comment]
> What if we first add support for AWS S3 and then we will tackle a way to have a CAS proxy? Or we need to do both at the same time?

We discussed this offline and there was a misunderstanding. The scope of this issue is not to change how Chainloop attestation process uses the CAS, but the internal implementation of the cas-proxy. How it could handle requests for different backends.
