### ISSUE TITLE
Helm chart deployment using GCP secret manager does not configure authentication properly

### ISSUE THREAD

**Issue by zaibon** [chainloop-dev/chainloop#295]
The code configuring the authentication to GCP Secret Manager expects the configuration to have a path to a service account file. https://github.com/Archipelo/chainloop-contrib/blob/a039a641688f6a76b1e443751035841b77ac3f13/internal/credentials/gcp/secretmanager.go#L70

But the hem chart does not upload a file, but just the content of secretsBackend.gcpSecretManager.authKey from the `values.yaml `file.
https://github.com/chainloop-dev/chainloop/blob/f6ec84dfc52b82515938ff1a3b51a4f2f32e3f50/deployment/chainloop/templates/_helpers.tpl#L82-L85

This could be fixed by mounting a k8s secret if the `authKey` is set and use the path mounted in the pod.

**Comment by migmartri** [comment]
Hi @zaibon, thanks for reporting the issue. As discussed [here](https://discord.com/channels/1037381970189111326/1037381970637897840/1140352546129580032), what you pointed out is indeed a bug in the Helm Chart. 

We are already looking into it and will target a fix on the next release of the chart. Thanks!
