### ISSUE TITLE
look into CLI panic error code handling

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#368]
We've noticed in some instances that a panic in the CLI didn't result in a failing job.

We need to look whether this is a CLI handling issue or a runner configuration

**Comment by danlishka** [comment]
@migmartri it was a problem with my script:

```
chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY 2>&1 | tee c8-push.txt
```

The pipe to `tee` was making the exit code `0`. False alarm. You can close this issue.

**Comment by migmartri** [comment]
Makes sense, thanks for checking
