### ISSUE TITLE
Install.sh does not support `aarch64`

### ISSUE THREAD

**Issue by buccarel** [chainloop-dev/chainloop#418]
This architecture is very common in docker containers that hosted by ARM architectures. A very common example is a container created within a macbook M1 or M2.

The following error is displayed when executing the script:

![image](https://github.com/chainloop-dev/chainloop/assets/11213785/22272e7c-fb2b-4657-aa28-b7a3fde34a30)

I believe the architecture could be treated as an alias for arm64. There are already [other developers that are using the same approach](https://github.com/fermyon/developer/blob/main/downloads/install.sh#L83C21-L83C21).

**Comment by migmartri** [comment]
just make sure that the binary we are already building for arm64 works in that case too https://github.com/chainloop-dev/chainloop/releases/tag/v0.25.0

**Comment by buccarel** [comment]
It works:
https://pastebin.com/BEVc7csz
