### ISSUE TITLE
Leaked Secret in internal/credentials/gcp/testdata/test_gcp_key.json

### ISSUE THREAD

**Issue by jesucuad-xyn** [chainloop-dev/chainloop#462]
Type: **private_key**

The issue was introduced on 2023-12-12T00:39:27.093+00:00 in:
- the component: **private_key**
- the specific location: **internal/credentials/gcp/testdata/test_gcp_key.json**

Private keys are the secret part in an asymmetric (public-private) keypair. They are used in different contexts and cryptographic applications.Most cryptography libraries use standard formats for private key exchange (like PEM )Public Keys and Public Key Certificates are public and have no sensitivity or confidentiality requirements (but do not accept a public key without trust on the link between the key and its owner).

Follow these http://docsdev.xygeni.io/xydocs/secrets/detectors/private_key.html

**Comment by migmartri** [comment]
Hi, thanks for creating the issue.

This is a false positive as discussed here https://github.com/chainloop-dev/chainloop/pull/124#discussion_r1205739203 

I am afraid that my original concerns about scanners getting confused are a reality. We'll look into alternative options.
