### ISSUE TITLE
feat: support optional parent project name/id for Dependency-Track SBOM upload 

### ISSUE THREAD

**Issue by sedan07** [chainloop-dev/chainloop#534]
Currently, you can configure the dependency-track integration to auto-create a project in Dependency-Track when uploading an SBOM. However, this auto-created project will just be at the top level of the hierarchy in Dependency-Track. For instances with many projects it can be useful to group them in a parent/child hierarchy. This requires passing an identifier for the parent project to the `/api/v1/bom` when submitting an SBOM which currently isn't supported in Chainloop.

Example project hierarchy in Dependency-Track:
![Example project hierarchy in Dependency-Track](https://user-images.githubusercontent.com/113189967/201305140-39e9879e-9e6e-43a4-9fee-ff7aa60ea720.png)

I might be able to find the time to submit a PR for this if this feature would be desirable and a PR welcome?

**Comment by migmartri** [comment]
hi @sedan07, thanks for posting the issue!

This is indeed a very useful feature, and we love contributions :)

Just some clarification. Chainloop allows you, as you mentioned, to attach a dependency-track project to a workflow, and this project can be either. 

- an existing one:  `projectID`
- an existing or new one: `projectName`  

```
┌───────────────────────────────────────────────────────────────────────────────────────────┐
│ Attachment inputs                                                                         │
├─────────────┬────────┬──────────┬─────────────────────────────────────────────────────────┤
│ FIELD       │ TYPE   │ REQUIRED │ DESCRIPTION                                             │
├─────────────┼────────┼──────────┼─────────────────────────────────────────────────────────┤
│ projectID   │ string │ no       │ The ID of the existing project to send the SBOMs to     │
│ projectName │ string │ no       │ The name of the project to create and send the SBOMs to │
└─────────────┴────────┴──────────┴─────────────────────────────────────────────────────────┘
 ```

The new `parentID` parameter will work in combination with `projectName` only, correct?

It also seems the parent [can be provided](https://docs.dependencytrack.org/usage/cicd/) either by name or id. Should we implement `parentName` as well? My gut feeling says that supporting parentID is the way to go for now, but I am curious about your use case.

## Where to start 

I know documentation could be better, so I'll try to point to the right places in the codebase to start with. I can also assist with the implementation if you want. You can find me in [Discord](https://discord.gg/2ymcSkbzjM).


This kind of functionality is implemented [as a fanOut plugin](https://github.com/chainloop-dev/chainloop/tree/main/app/controlplane/plugins), and specifically the DependencyTrack plugin can be found [here](https://github.com/chainloop-dev/chainloop/tree/main/app/controlplane/plugins/core/dependency-track/v1)

To add new parameters (i.e ParentID) to the attachment phase, you need to update this struct

https://github.com/chainloop-dev/chainloop/blob/3096036fa8ced1e38caf99e4bd06c523934c23b0/app/controlplane/plugins/core/dependency-track/v1/extension.go#L45-L49 

Once you do that, the user will have the option to provide such parameter using the chainloop CLI during attachment as shown [here](https://docs.chainloop.dev/guides/dependency-track/#2---attach-the-integration-to-a-workflow), basically `--opt parentID=deadbeef`

You can then retrieve such value in the plugin https://github.com/chainloop-dev/chainloop/blob/3096036fa8ced1e38caf99e4bd06c523934c23b0/app/controlplane/plugins/core/dependency-track/v1/extension.go#L122

and in there make sure to extend `validateAttachment` so it checks that the parent project exists, similarly of the validation that we do for the regular project 

https://github.com/chainloop-dev/chainloop/blob/3096036fa8ced1e38caf99e4bd06c523934c23b0/app/controlplane/plugins/core/dependency-track/v1/extension.go#L278

Finally, update the client and the execution phase to send these new parameters

https://github.com/chainloop-dev/chainloop/blob/3096036fa8ced1e38caf99e4bd06c523934c23b0/app/controlplane/plugins/core/dependency-track/v1/extension.go#L166

And that's it, don't forget to bump the plugin version and we are off to the races :)

https://github.com/chainloop-dev/chainloop/blob/3096036fa8ced1e38caf99e4bd06c523934c23b0/app/controlplane/plugins/core/dependency-track/v1/extension.go#L68

Thanks again!

**Comment by sedan07** [comment]
@migmartri thanks for the detailed breakdown of the changes required. I can certainly do these. 

> I know documentation could be better

So far actually I've been pleasantly surprised by the quality of the contribution documentation and local dev setup for a relatively young project.

**Comment by migmartri** [comment]
Great! Looking forward to the contribution. As I said, I am more than happy to assist, jump on a call, anything; you can find me here or in Discord.

> So far actually I've been pleasantly surprised by the quality of the contribution documentation and local dev setup for a relatively young project.

Glad to hear 😊

**Comment by migmartri** [comment]
hi @sedan07 

I just noticed that we've not documented this feature yet in https://docs.chainloop.dev/guides/dependency-track/

Is this something that you'd be interested in? 

The source code of the docs are also in this repo https://github.com/chainloop-dev/chainloop/tree/main/docs.

Since I noticed it's not documented, to run the docs site locally you'd do

```
# install dependencies
yarn install

# and run the site
yarn run docusaurus start 
```

Thanks!

**Comment by sedan07** [comment]
@migmartri I'd actually planned to update the docs then it completely slipped my mind. Yes I can sort that out.

**Comment by migmartri** [comment]
> @migmartri I'd actually planned to update the docs then it completely slipped my mind. Yes I can sort that out.

Thank you :)

**Comment by migmartri** [comment]
@sedan07, the documentation changes are now up again. Thanks!
