### ISSUE TITLE
feat: expose contract revision information

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#540]
We want to expose contract revision information in both the `workflowRun.List|Describe` endpoints and `workflow.List`

We want:

In the workflowRunList

- Show the revision number that was used
- And if it was the latest one at the time

In the workflow.List

- What's the latest available revision

**Comment by danlishka** [comment]
Instead of "And if it was the latest one at the time" - just add the workflow latest revision number. If wfRunUsedContractRev == wfRunLatestContractRev =? then it is the latest used. 

```
{
      "id": "b91b9fdc-c098-42fa-9873-90560cc0d1ee",
      "state": "success",
      "createdAt": "2024-02-20T11:32:52.109524Z",
      "finishedAt": "2024-02-20T11:41:18.648335Z",

      **contractUsedRev: 3**
      **latestContractRev: 4**

      "workflow": {
         "name": "build-and-test",
         "id": "0c497f60-de8d-402e-8caf-9975a61d4d14",
         "team": "core",
         "project": "chainloop-frontend",
         "createdAt": "2022-11-27T17:04:06.071739Z",
         "runsCount": 116,
         "public": false,

      **latestContractRev: 10**

      },
      "runnerType": "Unknown"
   }
```

**Comment by migmartri** [comment]
Why do you think it's better to add `**latestContractRev: 4**`. The reason I proposed to just indicate if it was `latest` is to make sure it's not confusing and can't be interpreted as the latest version available today. It is not, as you put in your example, it's the latest version available at that time.

TBH it's just a matter of usability, but your proposal might make sense if we want to detect the spread, is that what you have in mind. 

Either way I could implement either solution, no problem.

Thanks!
