### ISSUE TITLE
Handle AWS secret manager empty response 

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#56]
We've received this exception

```
{"level":"error", "msg":"runtime error: invalid memory address or nil pointer dereference: 
goroutine 25579 [running]:
github.com/go-kratos/kratos/v2/middleware/recovery.Recovery.func2.1.1()
	/home/runner/go/pkg/mod/github.com/go-kratos/kratos/v2@v2.5.3/middleware/recovery/recovery.go:53 +0xa7
panic({0x2185140, 0x3b16820})
	/opt/hostedtoolcache/go/1.20.2/x64/src/runtime/panic.go:884 +0x213
github.com/chainloop-dev/chainloop/internal/credentials/aws.(*Manager).ReadCredentials(0xc0006747b0, {0x28df088, 0xc000f01740}, {0xc000e8a660, 0x58}, {0x213dea0, 0xc000e0b2c0})
	/home/runner/work/chainloop/chainloop/internal/credentials/aws/secretmanager.go:123 +0x150
github.com/chainloop-dev/chainloop/internal/blobmanager/oci.(*BackendProvider).FromCredentials(0xc000752e20, {0x28df088, 0xc000f01740}, {0xc000e8a660, 0x58})
	/home/runner/work/chainloop/chainloop/internal/blobmanager/oci/provider.go:39 +0x93
github.com/chainloop-dev/chainloop/app/controlplane/internal/biz.(*OCIRepositoryUseCase).PerformValidation(0xc000704040, {0x28df088, 0xc000f01740}, {0xc0010e5260, 0x24})
```

The nil pointer is raised here 

https://github.com/chainloop-dev/chainloop/blob/08cd26fd89c0d6d653c201b5e7db296069e1a173/internal/credentials/aws/secretmanager.go#L123

It seems that for some reason both `resp` and `err` were nil?

**Comment by buccarel** [comment]
>It seems that for some reason both resp and err were nil?

When we check `if err != nil` we also do `if errors.As(err, &apiErr)`. If `err` cannot be asserted as of type `smithy.APIError`, the function does not return when it should, I believe.

**Comment by buccarel** [comment]
In fact, in the AWS documentation at this page:
https://aws.github.io/aws-sdk-go-v2/docs/migrating/

the following example can be found:
```
}
	var apiErr smithy.APIError
	if errors.As(err, &apiErr) {
		code := apiErr.ErrorCode()
		message := apiErr.ErrorMessage()
		// handle error code
		return
	}
	// handle error
	return
```
The code is implementing the block `// handle error code` but it's missing the block `// handle error`. At least, I think this is the cause of the problem.

**Comment by migmartri** [comment]
hi @buccarel, thanks for looking into this; I think you are right! We don't handle an error that's not an APIError 🤦🏼 

https://github.com/chainloop-dev/chainloop/blob/38505dc72147e018fa3d2ba33d40add579a37356/internal/credentials/aws/secretmanager.go#L112-L122

Would you like to add a patch for this? If so, ptal at the expected commit format in our [contribution guide](https://github.com/chainloop-dev/chainloop/blob/main/CONTRIBUTING.md)

Thank you!
