### ISSUE TITLE
Our install.sh script may not work on Alpine, CentOS

### ISSUE THREAD

**Issue by danlishka** [chainloop-dev/chainloop#587]
The `sha256sum` option `ignore-missing` might be missing on some Linux distributions: 

```
sha256sum: unrecognized option '--ignore-missing'
```

References:
- https://github.com/werf/werf/issues/1544
- https://github.com/werf/multiwerf/pull/31/files

**Comment by migmartri** [comment]
I just tried it at 

```
cat /etc/redhat-release 
CentOS Linux release 8.4.2105
```

and the option is there.

In alpine is not
