### ISSUE TITLE
chore(workflows): do not allow name update

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#683]
Because of moving to a more declarative approach based on the name of the resources, we don't want to allow users to change the name of workflows.

The goal of the task are:
- Remove the option from the CLI to update the name by passing the flag `--name`
- Modify GRPC services to don't accept the `Name` as parameter

**Comment by javirln** [comment]
I will do it in a breaking changing way, meaning not deprecation notice will be added to the CLI nor the field will be marked as deprecated on the service.
