### ISSUE TITLE
feat(referrers API): enable backlinks by default

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#703]
Currently, links between pieces of evidence and attestations are set only if they are part of the attestation subject. This was a decision based on limiting and scoping what elements can be root nodes in the graph. 

This decision has proven to be confusing to users, since in order to create union points, `output: true` was required to be added to the contract. 

I'd suggest that we do not rely on this casuistic and instead enable backlinks from materials to attestations in the referrer API denormalization always.

what do you think?

**Comment by danlishka** [comment]
+1 from me. We will review workflows linking/contracts soon. Thanks!
