### ISSUE TITLE
add ATTESTATION kind as material type

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#719]
In some cases, we might want to add additional attestations as pieces of evidence. This could help with storing externally generated attestations, or connecting different workflows in your organization.

To do so, we could add an ATTESTATION material type that will 

- get uploaded to the CAS
- we'll validate that's a valid DSSE envelope.
- we need to make sure that if we take an attestation from chainloop CLI and add it here as a material, it's still the same digest.
- NOTE: before ingesting this attestation type in the index, we might want to check that it is an existing attestation in your org. This is to make sure that nodes in the graph still represent attestations that have been generated with a run. Just some food for thought, I am not sure if we need this kind of optimization at this point, let's discuss it.

**Comment by migmartri** [comment]
I took a look at the digest matching.

We need to be careful, since the output of `wf run describe --id ... --output attestation does not match the sha256 of the attestation. This is because it's pretty printed.

For example

the generated output doesn't match the requested digest, it should

![Image](https://github.com/chainloop-dev/chainloop/assets/24523/124c76c6-8e68-40d4-baed-cf4c71c8490f)

the downloaded version does though


![Image](https://github.com/chainloop-dev/chainloop/assets/24523/32c79d5b-48b6-4778-b5c7-aafcab8d45be)


To make it match, what you need to do is to make the output single line

```
chainloop wf run describe --digest sha256:8b7c3bea8b640744762e7959a5f221a755fe28a8671d6ea9ff29ffa7625a3958 -o attestation | jq -c -r |  tr -d '\n' | sha256sum
8b7c3bea8b640744762e7959a5f221a755fe28a8671d6ea9ff29ffa7625a3958  -
```

So my suggestion would be to make sure we marshal the provided attestation in the client in such a way that fits the way we do it in the backend. 

We have a method that does that already but it's in the context of the controlplane.

https://github.com/chainloop-dev/chainloop/blob/7b1e79263dd68653a0a4010dec57235670f0d0a4/app/controlplane/internal/biz/attestation.go#L63

I'd move that method to the parent `internal/attestation` package, and use it from controlplane and CLI, to format the provided attestation, what do you think?

**Comment by jiparis** [comment]
Thanks for your analysis. Yes, this is certainly a problem that could be mitigated by creating the payload from the CLI using the same approach as the backend. Not a final solution, though. I'll perform the changes you suggest and submit a PR.
