### ISSUE TITLE
add missing binaries to the chainloop OSS release attestation

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#740]
The release attestation does not include all the binaries generated by go-releaser

This task is about them all

**Comment by javirln** [comment]
There are error during the attestation since apparently there are some materials not included in the contract:



![Image](https://github.com/chainloop-dev/chainloop/assets/4128269/2c4e0bad-dde7-4d1c-a8bf-c18b732ffa0f)
