### ISSUE TITLE
Implement attestation workflow

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#788]
Implement a workflow that translates github releases to chainloop attestations.

- It should work with a single API token
- It can create a workflow automatically
- It will download all the items of a release
- For each item, it will auto-detect (best effort) artifact types, i.e SBOM, .... or fallback to ARTIFACT
- will perform the attestation
- will add a link to the referenced release #787

**Comment by javirln** [comment]
Refs: https://github.com/chainloop-dev/chainloop/pull/822
