### ISSUE TITLE
Wrong kind detected

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#828]
```
chainloop att add --value ./internal/attestation/crafter/materials/testdata/sbom.cyclonedx.json
INF material kind detected kind=STRING
INF material added to attestation
```

This should have been an artifact.

**Comment by migmartri** [comment]
I believe this problem is because I am using an `inline` CAS backend, and the file went over the limit

During detection we should check first if we are failing because of size or because of detection.

cc/ @javirln

**Comment by javirln** [comment]
I will try to reproduce it locally.

**Comment by migmartri** [comment]
A problem that this issue surfaced is that our `string` kind doesn't have a max limit. We should add it and in that case the auto discovery will return error. Which is what we expected

**Comment by javirln** [comment]
How do you foresee to establish a max limit for the `STRING`, as far as I know the max limit is only set on the CAS backend and it's not configurable.

A default value on a contract's annotation that can be configurable?

**Comment by javirln** [comment]
What's your take? cc @jiparis
