### ISSUE TITLE
Make it a reusable workflow, implement it and document it

### ISSUE THREAD

**Issue by javirln** [chainloop-dev/chainloop#844]
The goal of the task is to provide a reusable workflow extract from the one introduced here: https://github.com/chainloop-dev/chainloop/pull/822

With the following:
- The reusable workflow needs to automatically onboard workflow if they don't exist by using the already existing reusable workflow: https://github.com/chainloop-dev/labs/blob/main/.github/workflows/chainloop_onboard.yml
- It needs to expose the same optional parameters as the previous workflow.
- It needs to accept a comma separated list of values as `additional_materials` that on top of the default materials being attested on the GitHub release, are added to the attestation.
- Only the `CHAINLOOP_TOKEN` is a required input to the workflow.

Why string list of values? Because there is no `array` type on GitHub workflows. A comma separated values will be used.

Document all the process in docs.chainloop.dev `guides` section.

**Comment by migmartri** [comment]
Makes sense to me. I'd make explicit that the only required parameter will be the CHAINLOOP_TOKEN
