### ISSUE TITLE
Support new attestation modality in Dagger Module

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#846]
Our dagger module doesn't support the modality where the workflow name is provided on `init`.

**Comment by javirln** [comment]
This task is blocked by this one: https://github.com/chainloop-dev/chainloop/issues/873

**Comment by javirln** [comment]
Blocked until we cut a new release of Chainloop.

**Comment by javirln** [comment]
I would add to the description the auto discovery option of the attestations.
