### ISSUE TITLE
Remote attestations using API tokens

### ISSUE THREAD

**Issue by javirln** [chainloop-dev/chainloop#873]
Chainloop supports attestations using a remote state on Chainloop's server. In order to support API tokens in the dagger module https://github.com/chainloop-dev/chainloop/issues/846, we need to allow API Tokens to use the remote state. This right now is failing probably due to some missing parsing/fetching on the information.

The goal of the task is:
- Be able to use an API token if the attestation uses a remote state.

**Comment by migmartri** [comment]
as discussed offline, it indeed seems that the `attestationstate` svc layer is only compatible with robot-accounts

```
robotAccount := usercontext.CurrentRobotAccount(ctx)
    if robotAccount == nil {
        return nil, errors.NotFound("not found", "robot account not found")
    }

    initialized, err := s.uc.Initialized(ctx, robotAccount.WorkflowID, req.WorkflowRunId)
    if err != nil {
        return nil, handleUseCaseErr(err, s.log)
    }
```

similarly to attestation the challenge is to find the workflow from two different sources, from the robot account or from the parameters through the run_id

so probably we can do smth similar to what we did in attestation, 
```
func (s *AttestationStateService) findWorkflowFromTokenOrRunID(ctx context.Context, orgID string, workflowID, runID string) (*biz.Workflow, error) { 
```

always making sure that this method checks that the run is part of the org.
