### ISSUE TITLE
error updating release notes

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#883]
The latest release job seems to fail due to the new `release action` trying to update the release notes

https://github.com/chainloop-dev/chainloop/actions/runs/9370415150/job/25797327665

It looks like a permission issue

```
HTTP 403: Resource not accessible by integration (https://api.github.com/repos/chainloop-dev/chainloop/releases/158835117)

```

cc/ @javirln

**Comment by javirln** [comment]
As per the information on the documentation, the only permission needed is `contents: write`

Ref: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release

I'll continue researching on what might be the problem.

**Comment by migmartri** [comment]
It seems we are only using `package: write` no?

**Comment by javirln** [comment]
> It seems we are only using `package: write` no?

I see there is `package: write` when setting up the job but the workflow file says otherwise:
https://github.com/chainloop-dev/chainloop/blob/c8be3eb2d16b4fa43d383093a00bfebd8c3cd9ef/.github/workflows/release.yaml#L7

Can this be a cache issue? It happened to me the other day while testing all this jobs.

**Comment by migmartri** [comment]
```
 release:
    name: Record release from GitHub
    runs-on: ubuntu-latest
    needs: onboard_workflow
    permissions:
      packages: write
```

there seems to also be a nested permissions, not sure how it works in that case though.

BTW, we need to review the jobs to make sure they are not using the top level permission, not following it is affecting our score, if I remember correctly I think we had that correctly setup in the past.

![image](https://github.com/chainloop-dev/chainloop/assets/24523/3e13d6c5-b88a-4069-a247-896b60e6952c)

**Comment by javirln** [comment]
> there seems to also be a nested permissions, not sure how it works in that case though.

In that case indeed it will take the most nested permission...that's the issue.

With regards on the scoring, we might need to review the rest of the jobs since there is a mixed between global and nested.
