### ISSUE TITLE
Pod fails to start on OpenShift: Error: runc create failed: unable to start container process: eaccess /atlas: permission denied

### ISSUE THREAD

**Issue by hanygirgis** [chainloop-dev/chainloop#922]
I'm trying to deploy Chainloop on an OpenShift environment, using a command similar to the following: 

helm install chainloop oci://ghcr.io/chainloop-dev/charts/chainloop \
    --set global.openshift=true \
    --set development=true \
    --set controlplane.auth.oidc.url=*url* \
    --set controlplane.auth.oidc.clientID=*client* \
    --set controlplane.auth.oidc.clientSecret=*secret* \
    --set controlplane.image.repository=*local*/chainloop/control-plane \
    --set controlplane.image.tag=v0.91.0 \
    --set controlplane.migration.image.repository=*local*/chainloop/control-plane-migrations \
    --set controlplane.migration.image.tag=v0.91.0 \
    --set cas.image.repository=*local*/chainloop/artifact-cas \
    --set cas.image.tag=v0.91.0
    
However, the **chainloop-controlplane** pod fails during initialization (Init:CreateContainerError) with error:
    
_Error: container create failed: time="2024-06-07T12:16:22Z" level=error msg="runc create failed: unable to start container process: eaccess /atlas: permission denied"_

Any idea how to solve this issue?

**Comment by migmartri** [comment]
Hi @hanygirgis.

Do you mind sharing some more information about your openshift environment? We are in the process of adding support of customizable `podsecuritycontext` that might be the culprit of your issue.

Thanks!

**Comment by hanygirgis** [comment]
Hi @migmartri,

I'm using this version:
```
OpenShift version: 4.13.27
Kubernetes version: v1.26.11
```
A suggestion is to maybe used the same `global.openshift` boolean flag that is used by Vault to configure the `podsecuritycontext`, to allow openshift compatibility with just one setting (if possible).

Thanks!

**Comment by migmartri** [comment]
That's a great pointer! Summoning @javirln, who's currently working on some Helm Chart changes to discuss next steps.

In any case, @hanygirgis we are open to contributions if you want to give it a try, we'll be happy to assist, either here at Github or also in our [Slack](https://join.slack.com/t/chainloop-community/shared_invite/zt-2k34dvx3r-u85uGP_KiLC6ic5Wy4aRnQ) :)

Thanks

**Comment by javirln** [comment]
> Thanks for the invitation : ) Sure, I'll be glad to contribute.

Hello @hanygirgis :)

We are migrating our current Chart approach to [Bitnami Charts](https://github.com/bitnami/charts). There, you can see how to set up pod security policies and container security policies, which we will need to add to our configurations.

Each chart includes a common chart that provides examples of how to inject these security policies. Since we are adopting Bitnami's contributing guidelines, this is the approach we should follow.

For an example, see how OpenShift is handled in this [helper](https://github.com/bitnami/charts/blob/4ee8ce7fe4a77814f8a9bdba5c7e5bdbf42fcd4a/bitnami/common/templates/_compatibility.tpl#L20).

 Aaand thank you so much for your interest on Chainloop :D

**Comment by hanygirgis** [comment]
Hello @javirln :) thanks for your answer.

I'm now checking the Bitnami compatibility helper you pointed to (but so far it's not clear what changes I need to make).

Initially I tried just setting runAsUser to 1001, but got _Forbidden: not usable by user or serviceaccount, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 1001: must be in the ranges: [1000880000, 1000889999]_

**Comment by hanygirgis** [comment]
It now works with helm chart 1.61.0 (and image versions v0.91.6)
Thanks a lot!

**Comment by migmartri** [comment]
Awesome, thanks for your help :)
