### ISSUE TITLE
support auto-onboarding users to organization

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#942]
It would be helpful if the chainloop instance could be configured so new users are automatically onboarded to a given organization(s).

For example this could be part of the configuration file and could look like

```bash
autoOnboarding:
  - org: my-org
    role: viewer
  - org: my-other-org
    role: admin
```

Once configured, when the user logs in, the system will

- Check if the org exist, if it does not, it will create it
- Create a membership for the current user to that organization with that role.

What do you think?

**Comment by javirln** [comment]
> Create a membership for the current user to that organization with that role.

There's a slight problem with this approach. If a user already belongs to the organization with one role, attempting to create a new membership with a different role will trigger a database constraint. This constraint ensures that only one role can exist for a given user and organization, which is logical.

If we want to update the role, we face another issue: the user attempting to update the role cannot be the same user who currently holds the membership.

My suggestion is as follows: If no membership exists, we apply the desired role. If this succeeds, great. If the user already has a membership for that organization, it may require an admin to update the role, and we do nothing further.

**Comment by migmartri** [comment]
> If we want to update the role, we face another issue: the user attempting to update the role cannot be the same user who currently holds the membership.

can you elaborate? Why can't our system change the role?

**Comment by migmartri** [comment]
In any case I think it's ok to not to override existing roles and take this as an `onboarding` for new users. Not a way to have a source of truth in code. Does it make sense?

**Comment by javirln** [comment]
> > If we want to update the role, we face another issue: the user attempting to update the role cannot be the same user who currently holds the membership.
> 
> can you elaborate? Why can't our system change the role?

Yes, basically is the following constraint: https://github.com/chainloop-dev/chainloop/blob/84ad7ed5807dd52b8b9d171855b739390333d372/app/controlplane/pkg/biz/membership.go#L159

> In any case I think it's ok to not to override existing roles and take this as an onboarding for new users. Not a way to have a source of truth in code. Does it make sense?

Yep, it makes total sense! :D

**Comment by migmartri** [comment]
> Yes, basically is the following constraint:

I see, but btw, remember, we can add as many use-cases as we need. In this case. That specific one is suited for users updating others, but we could have created another one that doesn't have that constraint. In any case, I think that skipping an update makes more sense in this case.
