### ISSUE TITLE
Support importing CA public key from a file

### ISSUE THREAD

**Issue by hanygirgis** [chainloop-dev/chainloop#956]
It would be nice to support loading a CA certificate from a file (e.g. by mounting a ConfigMap in Kubernetes) instead of manually baking it into the docker image.

Thanks!

**Comment by migmartri** [comment]
Thanks for the feature request. 

What is end purpose of this CA, is this solely to make the oidc discovery endpoint work?

**Comment by hanygirgis** [comment]
For now it is indeed to make the OIDC discovery endpoint work, as I'm getting this error during startup of the controlplane pod:

`panic: failed to create OIDC authenticator: Get "https://hostname/realms/Chainloop/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority`
